# Generated by Django 6.0.4 on 2026-04-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_subject_is_elective_subject_is_lab_studentelective"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentelective",
            unique_together=set(),
        ),
    ]
